ARCHS = arm64

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = QuadHighCurrent
QuadHighCurrent_FILES = Switch.xm
QuadHighCurrent_LIBRARIES = flipswitch
QuadHighCurrent_FRAMEWORKS = UIKit
QuadHighCurrent_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk