/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 8, 2019 at 1:25:15 PM Eastern European Standard Time
* Operating System: Version 12.1 (Build 16B92)
* Image Source: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SBFAuthenticationRequest : NSObject {

	unsigned long long _type;
	long long _source;
	/*^block*/id _handler;
	NSString* _passcode;

}

@property (nonatomic,readonly) unsigned long long type;               //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) long long source;                      //@synthesize source=_source - In the implementation block
@property (nonatomic,copy,readonly) NSString * passcode;              //@synthesize passcode=_passcode - In the implementation block
@property (nonatomic,copy,readonly) id handler;                       //@synthesize handler=_handler - In the implementation block
-(NSString *)passcode;
-(id)publicDescription;
-(id)_initWithType:(unsigned long long)arg1 source:(long long)arg2 passcode:(id)arg3 handler:(/*^block*/id)arg4 ;
-(id)initForPasscode:(id)arg1 source:(long long)arg2 handler:(/*^block*/id)arg3 ;
-(id)initForBiometricAuthenticationWithSource:(long long)arg1 handler:(/*^block*/id)arg2 ;
-(id)initForPasscode:(id)arg1 source:(long long)arg2 ;
-(id)initForBiometricAuthenticationWithSource:(long long)arg1 ;
-(id)succinctDescription;
-(id)descriptionWithMultilinePrefix:(id)arg1 ;
-(id)descriptionBuilderWithMultilinePrefix:(id)arg1 ;
-(id)succinctDescriptionBuilder;
-(id)description;
-(unsigned long long)type;
-(id)handler;
-(long long)source;
@end

