/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 8, 2019 at 1:24:42 PM Eastern European Standard Time
* Operating System: Version 12.1 (Build 16B92)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/


@class AVFlashlightInternal;

@interface AVFlashlight : NSObject {

	AVFlashlightInternal* _internal;

}

@property (getter=isAvailable,nonatomic,readonly) BOOL available; 
@property (getter=isOverheated,nonatomic,readonly) BOOL overheated; 
@property (nonatomic,readonly) float flashlightLevel; 
+(BOOL)hasFlashlight;
+(void)initialize;
-(void)_handleNotification:(id)arg1 payload:(id)arg2 ;
-(float)flashlightLevel;
-(void)_setupFlashlight;
-(void)_teardownFlashlight;
-(BOOL)isOverheated;
-(void)_reconnectToServer;
-(BOOL)turnPowerOnWithError:(id*)arg1 ;
-(void)turnPowerOff;
-(BOOL)setFlashlightLevel:(float)arg1 withError:(id*)arg2 ;
-(BOOL)isAvailable;
-(id)init;
-(void)dealloc;
@end

static AVFlashlight *fleshilght;
static BOOL flashlightEnabled = NO;

void toggleFlashlight() 
{
    if (flashlightEnabled) // if on
    {
        [fleshilght setFlashlightLevel:0 withError:nil];
        flashlightEnabled = NO;
    }
    else // if off
    {
        [fleshilght setFlashlightLevel:1 withError:nil];
        flashlightEnabled = YES;
    }

}

%hook UIWindow

- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent *)event
{
    %orig;
    if(event.type == UIEventSubtypeMotionShake && self == [[UIApplication sharedApplication] keyWindow])
    {
        toggleFlashlight();
    }
}

%end

%ctor 
{
	fleshilght = [[AVFlashlight alloc] init];
}